### ISSUE TITLE
Presentation for Receivoo App

### ISSUE THREAD

**Issue by Ark-003** [AngelPearl06/cc17-3f-yukuna#11]
The Canva Presentation is still incomplete, try to finish it until tomorrow.

To Do:
- [x] Problem
- [x] SDG Goal/s
- [x] SMART
- [x]  Features (Partially Completed)

Attached here is the canva link: https://www.canva.com/design/DAGQFhpWg2o/pPKba3mtgCkoz93gbam4Bw/edit

**Comment by Ark-003** [comment]
Tasks:
@AngelPearl06 - SDG Goals / Design Layout
@Ark-003 - SMART / Features
@SimonAquino - Problem / Design Layout
@Maxellla - Features / Design Layout

**Comment by SimonAquino** [comment]
noted

**Comment by Ark-003** [comment]
Any updates?

**Comment by SimonAquino** [comment]
Done with some designing and contents on my part(mga 9 something hehehe
)

**Comment by AngelPearl06** [comment]
Done ppt

**Comment by Ark-003** [comment]
Noted. Thankss
