### ISSUE TITLE
Sign Up Page for the Login UI

### ISSUE THREAD

**Issue by Ark-003** [AngelPearl06/cc17-3f-yukuna#12]
Please start working on the Sign Up part asap.

**Comment by SimonAquino** [comment]
![Image](https://github.com/user-attachments/assets/ebaf47a0-5da8-4ddb-ab0b-722989dcae93)
Done maybe missing just some elements

**Comment by SimonAquino** [comment]
oh also missing the logo

**Comment by SimonAquino** [comment]
![Image](https://github.com/user-attachments/assets/263c3e9a-711b-4ded-8edc-afed027c9447)

**Comment by SimonAquino** [comment]
waiting for the final logo uwu
