### ISSUE TITLE
Create UI Mockup for Login Screen

### ISSUE THREAD

**Issue by AngelPearl06** [AngelPearl06/cc17-3f-yukuna#5]

**Comment by SimonAquino** [comment]
Finding a color scheme

**Comment by Ark-003** [comment]
Done with the color scheme. Still working on the background color

**Comment by SimonAquino** [comment]
Still experimenting with log in and sign up buttons

**Comment by SimonAquino** [comment]
![Image](https://github.com/user-attachments/assets/1561ff04-901c-4745-a489-b24b9e14a5f3)
still experimenting (dont mind the logo HAHAHAHAHAH)

**Comment by Ark-003** [comment]
Looks good although the logo seems kinda out of place (?). Perhaps we can remove the white background to make it look coherent?

**Comment by SimonAquino** [comment]
updated the login
![Image](https://github.com/user-attachments/assets/cd4e383e-c606-4e19-80bc-1bbafabd4c82)

**Comment by SimonAquino** [comment]
added some animations

**Comment by SimonAquino** [comment]
just waiting for the final logo
