### ISSUE TITLE
Create UI Mockup for Planner

### ISSUE THREAD

**Issue by AngelPearl06** [AngelPearl06/cc17-3f-yukuna#8]

**Comment by Ark-003** [comment]
I need help with the concept for the manager. Any ideas?

**Comment by SimonAquino** [comment]
![Image](https://github.com/user-attachments/assets/dd31e7b5-0516-4be4-8c55-9f7da7d5cf04)


Possible layout o the planner ill add the details later

**Comment by SimonAquino** [comment]
also this 
![Image](https://github.com/user-attachments/assets/9a26ecfa-a155-4dab-81bf-c175e8ad3f92)

**Comment by SimonAquino** [comment]
![Image](https://github.com/user-attachments/assets/30742932-46f9-428d-88f4-7a2e64c15d12)

Another possible layout

**Comment by SimonAquino** [comment]
![Image](https://github.com/user-attachments/assets/8349d479-39b1-4fc0-8c3d-2c3adf8289f3)
This is the outcome of the reference layouts

**Comment by AngelPearl06** [comment]
Added more details, just a little more touch up

**Comment by AngelPearl06** [comment]
![Image](https://github.com/user-attachments/assets/1fa80e57-99ea-4dd6-af60-d0deca395814)
